"use client";

import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft } from "lucide-react";
import { PageHeader } from "@/components/layout/page-header";
import { PageLoader } from "@/components/layout/page-loader";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { headTeachersService } from "@/services/head-teachers.service";
import { formatDate } from "@/lib/utils";

export default function HeadTeacherQuizzesPage() {
  const quizzes = useQuery({
    queryKey: ["head-teacher-quizzes"],
    queryFn: () => headTeachersService.listQuizzes(),
  });

  if (quizzes.isLoading) {
    return (
      <div className="p-4 sm:p-6 lg:p-8">
        <PageHeader title="Quizzes" />
        <PageLoader variant="page" />
      </div>
    );
  }

  return (
    <div className="p-4 sm:p-6 lg:p-8">
      <PageHeader
        title="Quizzes"
        description="Quizzes generated by teachers in your supervised classes."
        actions={
          <Link href="/teacher/head">
            <Button variant="outline">
              <ArrowLeft className="h-4 w-4" />
              Back
            </Button>
          </Link>
        }
      />

      <div className="space-y-3">
        {(quizzes.data?.items ?? []).map((quiz) => (
          <article key={quiz.id} className="rounded-xl border bg-card p-4">
            <div className="flex flex-wrap items-center gap-2">
              <h2 className="font-semibold">{quiz.title}</h2>
              <Badge variant="secondary">{quiz.status}</Badge>
            </div>
            <p className="mt-1 text-sm text-muted-foreground">
              {quiz.teacherName}
              {quiz.classLabel ? ` · ${quiz.classLabel}` : ""}
              {quiz.subject?.name ? ` · ${quiz.subject.name}` : ""}
              {quiz.createdAt ? ` · ${formatDate(quiz.createdAt)}` : ""}
            </p>
          </article>
        ))}
        {!quizzes.data?.items.length ? (
          <p className="text-sm text-muted-foreground">No quizzes yet.</p>
        ) : null}
      </div>
    </div>
  );
}
